- name: Deploy Docker Container
  hosts: dockerservers
  gather_facts: false
  remote_user: root
  tasks:
    - name: Creating the Container
      docker_container:
        name: ok-container  # docker container name
        image: ok:latest   # docker image name
        ports:
          - "15000:80"  
        state: started
        restart: true
