- name: Deploy Docker Container
  hosts: dockerservers
  gather_facts: false
  remote_user: root
  tasks:
    - name: Creating the Container
      docker_container:
        name: KD-container  # docker container name
        image: KD:latest   # docker image name
        ports:
          - "12345:80"  
        state: started
        restart: true
